DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS user_rooms;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS users;

CREATE TABLE rooms (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT
);

CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  hash TEXT NOT NULL
);

CREATE TABLE messages (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms (id),
  user_id BIGINT REFERENCES users (id),
  message TEXT NOT NULL
);

CREATE TABLE user_rooms (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms (id),
  user_id BIGINT REFERENCES users (id)
);